### ISSUE TITLE
Generated "Has" queries should include "distinct" qualifier

### ISSUE THREAD

**Issue by samolds** [spacemonkeygo/dbx#30]
In my use of dbx, I am performing a `Has_` operation with a subquery that could have multiple results. Something to this effect:

```
SELECT COALESCE(( SELECT 1 FROM a WHERE a.user_id = ?),0)
```

If the subquery has multiple results, I get a:

```
pq: more than one row returned by a subquery used as an expression
```

One easy solution would be to include `DISTINCT` in the subquery.

This issue was discovered by @jrwren

**Comment by jrwren** [comment]
After a reading a bit, LIMIT 1 might be slightly nicer than DISTINCT.

**Comment by jrwren** [comment]
Looks fixed by https://github.com/spacemonkeygo/dbx/commit/172ea90d1f1449d078c4c712b10574790621b1ce

**Comment by zeebo** [comment]
Indeed it was.
