### ISSUE TITLE
I can project two keys with the same name and dbx generates invalid go

### ISSUE THREAD

**Issue by jrwren** [spacemonkeygo/dbx#34]
e.g.

```
read ( select t1 t2.id t3.id
  join t2.pk = t1.t2_pk
  join t4.pk = t2.t4_pk
  join t3.pk = t4.user_pk
)
```

generates a type with 2 Id fields.

```
type T1_Id_Id_Row struct {
	T1 T1
	Id                 string
	Id                 string
}
```

expected: 
It should error or name each field T2_ID and T3_ID.

actual:
Generates invalid Go.

**Comment by zeebo** [comment]
shoot good report. i guess specific fields need type prefixes

**Comment by jrwren** [comment]
It is very weird because I worked around it by changing the select to `t1 t2 t3.id` and the resulting struct names the `t3.id` field as `T3_Id`.
